
class Art:
    art25gpValue = ["Silver ewer",
	    "Carved bone statuette",
	    "Small gold bracelet",
	    "Cloth-of-gold vestments",
	    "Black velvet mask stitched with silver thread",
	    "Copper chalice with silver filigree",
	    "Pair of engraved bone dice",
	    "Small mirror set in a painted wooden frame",
	    "Embroidered silk handkerchief",
	    "Gold locket with a painted portrait inside"]

    art250gpValue = ["Gold ring set with bloodstones",
    	"Carved ivory statuette",
    	"Large gold bracelet",
    	"Silver necklace with a gemstone pendant",
    	"Bronze crown",
    	"Silk robe with gold embroidery",
    	"Large well-made tapestry",
    	"Brass mug with jade inlay",
    	"Box of turquoise animal figurines",
    	"Gold bird cage with electrum filigree"]

    art750gpValue = ["Silver chalice set with moonstones",
    	"Silver-plated steel longsword with jet set in hilt",
    	"Carved harp of exotic wood with ivory inlay and zircon gems",
    	"Small gold idol",
    	"Gold dragon comb set with red garnets as eyes",
    	"Bottle stopper cork embossed with gold leaf and set with amethysts",
    	"Ceremonial electrum dagger with a black pearl in the pommel",
    	"Silver and gold brooch",
    	"Obsidian statuette with gold fittings and inlay",
    	"Painted gold war mask"]

    art2500gpValue = ["Fine gold chain set with a fire opal",
    	"Old masterpiece painting",
    	"Embroidered silk and velvet mantle set with numerous moonstones",
    	"Platinum bracelet set with a sapphire",
    	"Embroidered glove set with jewel chips",
    	"Jeweled anklet",
    	"Gold music box",
    	"Gold circlet set with four aquamarines",
    	"Eye patch with a mock eye set in blue sapphire and moonstone",
    	"A necklace string of small pink pearls"]

    art7500gpValue = ["Jeweled gold crown",
    	"Jeweled platinum ring",
    	"Small gold statuette set with rubies",
    	"Gold cup set with emeralds",
    	"Gold jewelry box with platinum filigree",
    	"Painted gold child’s sarcophagus",
    	"Jade game board with solid gold playing pieces",
    	"Bejeweled ivory drinking horn with gold filigree"]

class Gems:
    gems10gpValue = ["Azurite (opaque mottled deep blue)",
        "Banded agate (translucent striped brown, blue, white, or red)",
        "Blue quartz (transparent pale blue)",
        "Eye agate (translucent circles or gray, white, brown, blue, or green)",
        "Hematite (opaque gray-black)",
        "Lapis lazuli (opaque light and dark blue with yellow flecks)",
        "Malachite (opaque striated light and dark green)",
        "Moss agate (translucent pink or yellow-white with mossy gray or green markings)",
        "Obsidian (opaque black)",
        "Rhodochrosite (opaque light pink)",
        "Tiger eye (translucent brown with golden center)",
        "Turquoise (opaque light blue-green)"]

    gems50gpValue = ["Bloodstone (opaque dark gray with red flecks)",
        "Carnelian (opaque orange to red-brown)",
        "Chalcedony (opaque white)",
        "Chrysoprase (translucent green)",
        "Citrine (transparent pale yellow-brown)",
        "Jasper (opaque blue, black, or brown)",
        "Moonstone (translucent white with pale blue glow)",
        "Onyx (opaque bands of black and white, or pure black or white)",
        "Quartz (transparent white, smoky gray, or yellow)",
        "Sardonyx (opaque bands of red and white)",
        "Star rose quartz (translucent rosy stone with white star-shaped center)",
        "Zircon (transparent pale blue-green)"]

    gems100gpValue = ["Amber (transparent watery gold to rich gold)",
    	"Amethyst (transparent deep purple)",
    	"Chrysoberyl (transparent yellow-green to pale green)",
    	"Coral (opaque crimson)",
    	"Garnet (transparent red, brown-green, or violet)",
    	"Jade (translucent light green, deep green, or white)",
    	"Jet (opaque deep black)",
    	"Pearl (opaque lustrous white, yellow, or pink)",
    	"Spinel (transparent red, red-brown, or deep green)",
    	"Tourmaline (transparent pale green, blue, brown, or red)"]

    gems500gpValue = ["Alexandrite (transparent dark green)",
    	"Aquamarine (transparent pale blue-green)",
    	"Black pearl (opaque pure black)",
    	"Blue spinel (transparent deep blue)",
    	"Peridot (transparent rich olive green)",
    	"Topaz (transparent golden yellow)"]

    gems1000gpValue = ["Black opal (translucent dark green with black mottling and golden flecks)",
    	"Blue sapphire (transparent blue-white to medium blue)",
    	"Emerald (transparent deep bright green)",
    	"Fire opal (translucent fiery red)",
    	"Opal (translucent pale blue with green and golden mottling)",
    	"Star ruby (translucent ruby with white star-shaped center)",
    	"Star sapphire (translucent blue sapphire with white star-shaped center)",
    	"Yellow sapphire (transparent fiery yellow or yellow-green)"]

    gems5000gpValue = ["Black sapphire (translucent lustrous black with glowing highlights)",
    	"Diamond (transparent blue-white, canary, pink, brown, or blue)",
    	"Jacinth (transparent fiery orange)",
    	"Ruby (transparent clear red to deep crimson)"]

class MagicItems:
    tableA = ("Potion of healing",
        "Spell scroll (cantrip)",
    	"Potion of climbing",
    	"Spell scroll (1st level)",
    	"Spell scroll (2nd level)",
    	"Potion of greater healing",
    	"Bag of holding",
    	"Driftglobe")

    tableB = ("Potion of greater healing",
    	"Potion of fire breath",
    	"Potion of resistance",
    	"Ammunition, +1",
    	"Potion of animal friendship",
    	"Potion of hill giant strength",
    	"Potion of growth",
    	"Potion of water breathing",
    	"Spell scroll (2nd level)",
    	"Spell scroll (3rd level)",
    	"Bag of holding",
    	"Keoghtom's ointment",
    	"Oil of slipperiness",
    	"Dust of disappearance",
    	"Dust of dryness",
    	"Dust of sneezing and choking",
    	"Elemental gem",
    	"Philter of love",
    	"Alchemy jug",
    	"Cap of water breathing",
    	"Cloak of the manta ray",
    	"Driftglobe",
    	"Goggles of night",
    	"Helm of comprehending languages",
    	"Immovable rod",
    	"Lantern of revealing",
    	"Mariner's armor",
    	"Mithral armor",
    	"Potion of poison",
    	"Ring of swimming",
    	"Robe of useful items",
    	"Rope of climbing",
    	"Saddle of the cavalier",
    	"Wand of magic detection",
    	"Wand of secrets")

    tableC = ("Potion of superior healing",
    	"Spell scroll (4thlevel)",
    	"Ammunition, +2",
    	"Potion of clairvoyance",
    	"Potion of diminution",
    	"Potion of gaseous form",
    	"Potion of frost giant strength",
    	"Potion of stone giant strength",
    	"Potion of heroism",
    	"Potion of invulnerability",
    	"Potion of mind reading",
    	"Spell scroll (5thlevel)",
    	"Elixir of health",
    	"Oil of etherealness",
    	"Potion of fire giant strength",
    	"Quaal's feather token",
    	"Scroll of protection",
    	"Bag of beans",
    	"Bead of force",
    	"Chime of opening",
    	"Decanter of endless water",
    	"Eyes of minute seeing",
    	"Folding boat",
    	"Heward's handy haversack",
    	"Horseshoes of speed",
    	"Necklace of fireballs",
    	"Periapt of health",
    	"Sending Stones")

    tableD = ("Potion of supreme healing",
    	"Potion of invisibility",
    	"Potion of speed",
    	"Spell scroll (6thlevel)",
    	"Spell scroll (7thlevel)",
    	"Ammunition, +3",
    	"Oil of sharpness",
    	"Potion of flying",
    	"Potion of cloud giant strength",
    	"Potion of longevity",
    	"Potion of vitality",
    	"Spell scroll (8thlevel)",
    	"Horseshoes of a zephyr",
    	"Nolzur's marvelous pigments",
    	"Bag of devouring",
    	"Portable hole")
    
    tableE = ("Spell scroll (8thlevel)",
    	"Potion of storm giant strength",
    	"Poti on of supreme healing",
    	"Spell scroll (9st level)",
    	"Universal solvent",
    	"Arrow of slaying",
    	"Sovereign glue")

    tableF = ("Weapon, +1",
    	"Shield,+ 1",
    	"Sentinel shield",
    	"Amulet of proof against detection and location",
    	"Boots of elvenkind",
    	"Boots of striding and springing",
    	"Bracers of archery",
    	"Brooch of shielding",
    	"Broom of flying",
    	"Cloak of elvenkind",
    	"Cloak of protection",
    	"Gauntlets of ogre power",
    	"Hat of disguise",
    	"Javelin of lightning",
    	"Pearl of power",
    	"Rod of the pact keeper, + 1",
    	"Slippers of spider climbing",
    	"Staff of the adder",
    	"Staff of the python",
    	"Sword of vengeance",
    	"Trident of fish command",
    	"Wand of magic missiles",
    	"Wand of the war mage, + 1",
    	"Wand of web",
    	"Weapon of warning",
    	"Adamantine armor (chain mail)",
    	"Adamantine armor (chain shirt)",
    	"Adamantine armor (scale mail)",
    	"Bag of tricks (gray)",
    	"Bag of tricks (rust)",
    	"Bag of tricks (tan)",
    	"Boots of the winterlands",
    	"Circlet of blasting",
    	"Deck of illusions",
    	"Eversmoking bottle",
    	"Eyes of charming",
    	"Eyes of the eagle",
    	"Figurine of wondrous power (silver raven)",
    	"Gem of brightness",
    	"Gloves of missile snaring",
    	"Gloves of swimming and climbing",
    	"Gloves of thievery",
    	"Headband of intellect",
    	"Helm of telepathy",
    	"Instrument of the bards (Doss lute)",
    	"Instrument of the bards (Fochlucan bandore)",
    	"Instrument of the bards (Mac-Fuimidh cittern)",
    	"Medallion of thoughts",
    	"Necklace of adaptation",
    	"Periapt of wound closure",
    	"Pipes of haunting",
    	"Pipes of the sewers",
    	"Ring of jumping",
    	"Ring of mind shielding",
    	"Ring of warmth",
    	"Ring of water walking",
    	"Quiver of Ehlonna",
    	"Stone of good luck",
    	"Wind fan",
    	"Winged boots")

    tableG = ("Weapon, +2",
        "Figurine of wondrous power",
        "Adamantine armor (breastplate)",
        "Adamantine armor (splint)",
        "Amulet of health",
    	"Armor of vulnerability",
    	"Arrow-catching shield",
    	"Belt of dwarvenkind",
    	"Belt of hill giant strength",
    	"Berserker axe",
    	"Boots of levitation",
    	"Boots of speed",
    	"Bowl of commanding water elementals",
    	"Bracers of defense",
    	"Brazier of commanding fire elementals",
    	"Cape of the mountebank",
    	"Censer of controlling air elementals",
    	"Armor, +1 chain mail",
    	"Armor of resistance (chain mail)",
    	"Armor, +1 chain shirt",
    	"Armor of resistance (chain shirt)",
    	"Cloak of displacement",
    	"Cloak of the bat",
    	"Cube of force",
    	"Daern’s instant fortress",
    	"Dagger of venom",
    	"Dimensional shackles",
    	"Dragon slayer",
    	"Elven chain",
    	"Flame tongue",
    	"Gem of seeing",
    	"Giant slayer",
    	"Glamoured studded leather",
    	"Helm of teleportation",
    	"Horn of blasting",
    	"Horn of Valhalla (silver or brass)",
    	"Instrument of the bards (Canaith mandolin)",
    	"Instrument of the bards (Cli lyre)",
    	"Ioun stone (awareness)",
    	"Ioun stone (protection)",
    	"Ioun stone (reserve)",
    	"Ioun stone (sustenance)",
    	"Iron bands of Bilarro",
    	"Armor, +1 leather",
    	"Armor of resistance (leather)",
    	"Mace of disruption",
    	"Mace of smiting",
    	"Mace of terror",
    	"Mantle of spell resistance",
    	"Necklace of prayer beads",
    	"Periapt of proof against poison",
    	"Ring of animal influence",
    	"Ring of evasion",
    	"Ring of feather falling",
    	"Ring of free action",
    	"Ring of protection",
    	"Ring of resistance",
    	"Ring of spell storing",
    	"Ring of the ram",
    	"Ring of X-ray vision",
    	"Robe of eyes",
    	"Rod of rulership",
    	"Rod of the pact keeper, +2",
    	"Rope of entanglement",
    	"Armor, +1 scale mail",
    	"Armor of resistance (scale mail)",
    	"Shield, +2",
    	"Shield of missile attraction",
    	"Staff of charming",
        "Staff of healing",
    	"Staff of swarming insects",
    	"Staff of the woodlands",
    	"Staff of withering",
    	"Stone of controlling earth elementals",
    	"Sun blade",
    	"Sword of life stealing",
    	"Sword of wounding",
    	"Tentacle rod",
    	"Vicious weapon",
    	"Wand of binding",
    	"Wand of enemy detection",
    	"Wand of fear",
    	"Wand of fireballs",
    	"Wand of lightning bolts",
    	"Wand of paralysis",
    	"Wand of the war mage, +2",
    	"Wand of wonder",
    	"Wings of flying")

    tableH = ("Weapon, +3",
        "Amulet of the planes",
    	"Carpet of flying",
    	"Crystal ball (very rare version)",
    	"Ring of regeneration",
       	"Ring of shooting stars",
    	"Ring of telekinesis",
    	"Robe of scintillating colors",
    	"Robe of stars",
    	"Rod of absorption",
    	"Rod of alertness",
    	"Rod of security",
    	"Rod of the pact keeper, +3",
    	"Scimitar of speed",
    	"Shield, +3",
    	"Staff of fire",
    	"Staff of frost",
    	"Staff of power",
    	"Staff of striking",
    	"Staff of thunder and lightning",
    	"Sword of sharpness",
    	"Wand of polymorph",
    	"Wand of the war mage, +3",
    	"Adamantine armor (half plate)",
    	"Adamantine armor (plate)",
    	"Animated shield",
    	"Belt of fire giant strength",
    	"Belt of frost giant strength (or stone)",
    	"Armor, +1 breastplate",
    	"Armor of resistance (breastplate)",
    	"Candle of invocation",
    	"Armor, +2 chain mail",
    	"Armor, +2 chain shirt",
    	"Cloak of arachnida",
    	"Dancing sword",
    	"Demon armor",
    	"Dragon scale mail",
    	"Dwarven plate",
    	"Dwarven thrower",
    	"Efreeti bottle",
    	"Figurine of wondrous power (obsidian steed)",
    	"Frost brand",
    	"Helm of brilliance",
    	"Horn of Valhalla (bronze)",
    	"Instrument of the bards (Anstruth harp)",
    	"Ioun stone (absorption)",
    	"Ioun stone (agility)",
    	"Ioun stone (fortitude)",
    	"Ioun stone (insight)",
    	"Ioun stone (intellect)",
    	"Ioun stone (leadership)",
    	"Ioun stone (strength)",
    	"Armor, +2 leather",
    	"Manual of bodily health",
    	"Manual of gainful exercise",
    	"Manual of golems",
    	"Manual of quickness of action",
    	"Mirror of life trapping",
    	"Nine lives stealer",
    	"Oathbow",
    	"Armor, +2 scale mail",
    	"Spellguard shield",
    	"Armor, +1 splint",
    	"Armor of resistance (splint)",
    	"Armor, +1 studded leather",
    	"Armor of resistance (studded leather)",
    	"Tome of clear thought",
    	"Tome of leadership and influence",
    	"Tome of understanding")

    tableI = ("Defender",
    	"Hammer of thunderbolts",
    	"Luck blade",
    	"Sword of answering",
    	"Holy avenger",
    	"Ring of djinni summoning",
    	"Ring of invisibility",
    	"Ring of spell turning",
    	"Rod of lordly might",
    	"Staff of the magi",
    	"Vorpal sword",
    	"Belt of cloud giant strength",
    	"Armor, +2 breastplate",
    	"Armor, +3 chain mail",
    	"Armor, +3 chain shirt",
    	"Cloak of invisibility",
    	"Crystal ball (legendary version)",
    	"Armor, +1 half plate",
    	"Iron flask",
    	"Armor, +3 leather",
    	"Armor, +1 plate",
    	"Robe of the archmagi",
    	"Rod of resurrection",
    	"Armor, +1 scale mail",
    	"Scarab of protection",
    	"Armor, +2 splint",
    	"Armor, +2 studded leather",
    	"Well of many worlds",
    	"Magic armor",
    	"Apparatus of Kwalish",
    	"Armor of invulnerability",
    	"Belt of storm giant strength",
    	"Cubic gate",
    	"Deck of many things",
    	"Efreeti chain",
    	"Armor of resistance (half plate)",
    	"Horn of Valhalla (iron)",
    	"Instrument of the bards (Ollamh harp)",
    	"Ioun stone (greater absorption)",
    	"Ioun stone (mastery)",
    	"Ioun stone (regeneration)",
    	"Plate armor of etherealness",
    	"Armor of resistance (plate)",
    	"Ring of air elemental command",
    	"Ring of earth elemental command",
    	"Ring of fire elemental command",
    	"Ring of three wishes",
    	"Ring of water elemental command",
    	"Sphere of annihilation",
    	"Talisman of pure good",
    	"Talisman of the sphere",
    	"Talisman of ultimate evil",
    	"Tome of the stilled tongue")

    figurines = (" (Bronze griffon)",
        " (Ebony fly)",
        " (Golden lions)",
        " (Ivory goats)",
        " (Marble elephant)",
        " (Onyx dog)",
        " (Serpentine owl)")

    magicArmor = ("Armor, +2 half plate",
        "Armor, +2 plate",
        "Armor, +3 studded leather",
        "Armor, +3 breastplate",
        "Armor, +3 splint",
        "Armor, +3 half plate",
        "Armor, +3 plate")

class Spells:
    cantrips = ("Acid Splash",
        "Blade Ward",
        "Booming Blade",
        "Chill Touch",
        "Control Flames",
        "Create Bonfire",
        "Dancing Lights",
        "Druidcraft",
        "Eldritch Blast",
        "Fire Bolt",
        "Friends",
        "Frostbite",
        "Green Flame Blade",
        "Guidance",
        "Gust",
        "Light",
        "Lightning Lure",
        "Mage Hand",
        "Magic Stone",
        "Mending",
        "Message",
        "Minor Illusion",
        "Mold Earth",
        "Poison Spray",
        "Prestidigitation",
        "Produce Flame",
        "Psychotic Episode",
        "Ray Of Frost",
        "Resistance",
        "Sacred Flame",
        "Shape Water",
        "Shillelagh",
        "Shocking Grasp",
        "Spare The Dying",
        "Sword Burst",
        "Thaumaturgy",
        "Thorn Whip",
        "Thunderclap",
        "Touch Of Madness",
        "True Strike",
        "Vicious Mockery")

    level1Spells = ("Absorb Elements",
        "Alarm",
        "Animal Friendship",
        "Armor Of Agathys",
        "Bane",
        "Beast Bond",
        "Bless",
        "Burning Hands",
        "Ceremony",
        "Charm Person",
        "Chromatic Orb",
        "Color Spray",
        "Command",
        "Compelled Duel",
        "Comprehend Languages",
        "Create Or Destroy Water",
        "Cure Wounds",
        "Detect Evil And Good",
        "Detect Magic",
        "Detect Poison And Disease",
        "Disguise Self",
        "Dissonant Whispers",
        "Divine Favor",
        "Earth Tremor",
        "Ensnaring Strike",
        "Entangle",
        "Expeditious Retreat",
        "Faerie Fire",
        "False Life",
        "Feather Fall",
        "Find Familiar",
        "Fog Cloud",
        "Goodberry",
        "Grease",
        "Guiding Bolt",
        "Hail Of Thorns",
        "Healing Word",
        "Hellish Rebuke",
        "Heroism",
        "Hex",
        "Hunters Mark",
        "Ice Knife",
        "Identify",
        "Illusory Script",
        "Inflict Wounds",
        "Jump",
        "Longstrider",
        "Mage Armor",
        "Magic Missile",
        "Protection From Evil And Good",
        "Purify Food And Drink",
        "Ray Of Sickness",
        "Sanctuary",
        "Searing Smite",
        "Shield",
        "Shield Of Faith",
        "Silent Image",
        "Sleep",
        "Speak With Animals",
        "Tasha's Hideous Laughter",
        "Tenser's Floating Disk",
        "Thunderous Smite",
        "Thunderwave",
        "Unseen Servant",
        "Witch Bolt",
        "Wrathful Smite")

    level2Spells = ("Aganazzar S Scorcher",
        "Aid",
        "Alter Self",
        "Animal Messenger",
        "Arcane Lock",
        "Augury",
        "Barkskin",
        "Beast Sense",
        "Blindness deafness",
        "Blur",
        "Branding Smite",
        "Calm Emotions",
        "Cloud Of Dagger",
        "Continual Flame",
        "Cordon Of Arrows",
        "Crown Of Madness",
        "Darkness",
        "Darkvision",
        "Detect Thoughts",
        "Dust Devil",
        "Earthbind",
        "Enhance Ability",
        "Enlarge / Reduce",
        "Enthrall",
        "Find Steed",
        "Find Traps",
        "Flame Blade",
        "Flaming Sphere",
        "Gentle Repose",
        "Gust Of Wind",
        "Heat Metal",
        "Hold Person",
        "Invisibility",
        "Knock",
        "Lesser Restoration",
        "Levitate",
        "Locate Animals Or Plants",
        "Locate Object",
        "Magic Mouth",
        "Magic Weapon",
        "Maximilian S Earthen Grasp",
        "Melf's Acid Arrow",
        "Mirror Image",
        "Misty Step",
        "Moonbeam",
        "Nystul's Magic Aura",
        "Pass Without Trace",
        "Phantasmal Force",
        "Prayer Of Healing",
        "Protection From Poison",
        "Pyrotechnics",
        "Ray Of Enfeeblement",
        "Rope Trick",
        "Scorching Ray",
        "See Invisibility",
        "Shatter",
        "Silence",
        "Skywrite",
        "Snilloc's Snowball Swarm",
        "Spider Climb",
        "Spike Growth",
        "Spiritual Weapon",
        "Suggestion",
        "Warding Bond",
        "Warding Wind",
        "Web",
        "Zone Of Truth")

    level3Spells = ("Animate Dead",
        "Aura Of Vitality",
        "Beacon Of Hope",
        "Bestow Curse",
        "Blinding Smite",
        "Blink",
        "Call Lightning",
        "Clairvoyance",
        "Conjure Animals",
        "Conjure Barrage",
        "Counterspell",
        "Create Food And Water",
        "Crusader S Mantle",
        "Daylight",
        "Dispel Magic",
        "Elemental Weapon",
        "Erupting Earth",
        "Fear",
        "Feign Death",
        "Fireball",
        "Flame Arrows",
        "Fly",
        "Gaseous Form",
        "Glyph Of Warding",
        "Haste",
        "Hunger Of Hadar",
        "Hypnotic Pattern",
        "Leomund S Tiny Hut",
        "Lightning Arrow",
        "Lightning Bolt",
        "Magic Circle",
        "Major Image",
        "Mass Healing Word",
        "Meld Into Stone",
        "Melf's Minute Meteors",
        "Nondetection",
        "Phantom Steed",
        "Plant Growth",
        "Protection From Energy",
        "Remove Curse",
        "Revivify",
        "Sending",
        "Sleet Storm",
        "Slow",
        "Speak With Dead",
        "Speak With Plants",
        "Spirit Guardians",
        "Stinking Cloud",
        "Tidal Wave",
        "Tongues",
        "Vampiric Touch",
        "Wall Of Sand",
        "Wall Of Water",
        "Water Breathing",
        "Water Walk",
        "Wind Wall")

    level4Spells = ("Arcane Eye",
        "Aura Of Life",
        "Aura Of Purity",
        "Banishment",
        "Blight",
        "Compulsion",
        "Confusion",
        "Conjure Minor Elementals",
        "Conjure Woodland Beings",
        "Control Water",
        "Death Ward",
        "Dimension Door",
        "Divination",
        "Dominate Beast",
        "Elemental Bane",
        "Evard's Black Tentacles",
        "Fabricate",
        "Find Greater Steed",
        "Fire Shield",
        "Freedom Of Movement",
        "Giant Insect",
        "Grasping Vine",
        "Greater Invisibility",
        "Guardian Of Faith",
        "Hallucinatory Terrain",
        "Ice Storm",
        "Leomund's Secret Chest",
        "Locate Creature",
        "Mordenkainen's Faithful Hound",
        "Mordenkainen's Private Sanctum",
        "Otiluke's Resilient Sphere",
        "Phantasmal Killer",
        "Polymorph",
        "Staggering Smite",
        "Stone Shape",
        "Stoneskin",
        "Storm Sphere",
        "Vitriolic Sphere",
        "Wall Of Fire",
        "Watery Sphere")

    level5Spells = ("Animate Objects",
    	"Antilife Shell",
    	"Arcane Hand",
       	"Awaken",
    	"Banishing Smite",
    	"Circle Of Power",
    	"Cloudkill",
    	"Commune",
    	"Commune With Nature",
    	"Cone Of Cold",
    	"Conjure Elemental",
    	"Conjure Volley",
    	"Contact Other Plane",
    	"Contagion",
    	"Control Winds",
    	"Creation",
    	"Destructive Wave",
    	"Dispel Evil And Good",
      	"Dominate Person",
    	"Dream",
    	"Flame Strike",
       	"Geas",
    	"Greater Restoration",
    	"Hallow",
    	"Hold Monster",
    	"Immolation",
    	"Insect Plague",
    	"Legend Lore",
    	"Maelstrom",
    	"Mass Cure Wounds",
    	"Mislead",
    	"Modify Memory",
    	"Passwall",
    	"Planar Binding",
    	"Raise Dead",
    	"Reincarnate",
        "Scrying",
    	"Seeming",
    	"Swift Quiver",
    	"Telekinesis",
    	"Telepathic Bond",
    	"Teleportation Circle",
    	"Transmute Rock",
    	"Tree Stride",
    	"Wall Of Force",
    	"Wall Of Stone")

    level6Spells = ("Arcane Gate",
        "Blade Barrier",
        "Bones of the Earth",
        "Chain Lightning",
        "Circle Of Death",
        "Conjure Fey",
        "Contingency",
        "Create Undead",
        "Disintegrate",
        "Eyebite",
        "Find The Path",
        "Flesh To Stone",
        "Forbiddance",
        "Freezing Sphere",
        "Globe Of Invulnerability",
        "Guards And Wards",
        "Harm",
        "Heal",
        "Heroes' Feast",
        "Instant Summons",
        "Investiture of Flame",
        "Investiture of Ice",
        "Investiture of Stone",
        "Investiture of Wind",
        "Irresistible Dance",
        "Magic Jar",
        "Mass Suggestion",
        "Move Earth",
        "Planar Ally",
        "Primordial Ward",
        "Programmed Illusion",
        "Sunbeam",
        "Transport Via Plants",
        "True Seeing",
        "Wall Of Ice",
        "Wall Of Thorns",
        "Wind Walk",
        "Word Of Recall")

    level7Spells = ("Arcane Sword",
        "Conjure Celestial",
        "Delayed Blast Fireball",
        "Divine Word",
        "Etherealness",
        "Finger Of Death",
        "Fire Storm",
        "Forcecage",
        "Magnificent Mansion",
        "Mirage Arcane",
        "Plane Shift",
        "Prismatic Spray",
        "Project Image",
        "Regenerate",
        "Resurrection",
        "Reverse Gravity",
        "Sequester",
        "Simulacrum",
        "Symbol",
        "Teleport",
        "Whirlwind")

    level8Spells = ("Animal Shapes",
        "Antimagic Field",
        "Antipathy/sympathy",
        "Clone",
        "Control Weather",
        "Demiplane",
        "Dominate Monster",
        "Earthquake",
        "Feeblemind",
        "Glibness",
        "Holy Aura",
        "Horrid Wilting",
        "Incendiary Cloud",
        "Maze",
        "Mind Blank",
        "Power Word Stun",
        "Sunburst",
        "Telepathy",
        "Tsunami")

    level9Spells = ("Astral Projection",
        "Foresight",
        "Gate",
        "Imprisonment",
        "Mass Heal",
        "Meteor Swarm",
        "Power Word Heal",
        "Power Word Kill",
        "Prismatic Wall",
        "Shapechange",
        "Storm Of Vengeance",
        "Time Stop",
        "True Polymorph",
        "True Resurrection",
        "Weird",
        "Wish")

class MagicProperties:
    creator = ("Aberration\n"
        " The item was created by aberrations in ancient times, possibly for the use of\n"
        " favored humanoid thralls. When seen from the corner of the eye, the item seems to\n"
        " be moving.",

    	"Human\n"
        " The item was created during the heyday of a fallen human kingdom, or it is tied to a\n"
        " human of legend. It might hold writing in a forgotten tongue or symbols whose\n"
        " significance is lost to the ages.",

    	"Celestial\n"
        " The weapon is half the normal weight and inscribed with feathered wings, suns, and\n"
        " other symbols of good. Fiends find the item’s presence repulsive.",

    	"Dragon\n"
        " This item is made from scales and talons shed by a dragon. Perhaps it incorporates\n"
        " precious metals and gems from the dragon’s hoard. It grows slightly warm when within\n"
        " 120 feet of a dragon.",

    	"Drow\n"
        " The item is half the normal weight. It is black and inscribed with spiders and webs in\n"
        " honor of Lolth. It might function poorly, or disintegrate, if exposed to sunlight\n"
        " for 1 minute or more.",

    	"Dwarf\n"
        " The item is durable and has Dwarven runes worked into its design. It might be\n"
        " associated with a clan that would like to see it returned to their ancestral halls.",

    	"Elemental Air\n"
        " The item is half the normal weight and feels hollow. If it’s made of fabric, it is\n"
        " diaphanous.",

    	"Elemental Earth\n"
        " This item might be crafted from stone. Any cloth or leather elements are studded with\n"
        " finely polished rock.",

    	"Elemental Fire\n"
        " This item is warm to the touch, and any metal parts are crafted from black iron.\n"
        " Sigils of flames cover its surface. Shades of red and orange are the prominent colors.",

    	"Elemental Water\n"
        " Lustrous fish scales replace leather or cloth on this item, and metal portions are\n"
        " instead crafted from seashells and worked coral as hard as any metal.",

    	"Elf\n"
        " The item is half the normal weight. It is adorned with symbols of nature: leaves,\n"
        " vines, stars, and the like.",

    	"Fey\n"
        " The item is exquisitely crafted from the finest materials and glows with a pale\n"
        " radiance in moonlight, shedding dim light in a 5-foot radius. Any metal in the item\n"
        " is silver or mithral, rather than iron or steel.",

    	"Fiend\n"
        " The item is made of black iron or horn inscribed with runes, and any cloth or leather\n"
        " components are crafted from the hide of fiends. It is warm to the touch and features\n"
        " leering faces or vile runes engraved on its surface. Celestials find the item’s\n"
        " presence repulsive.",

    	"Giant\n"
        " The item is larger than normal and was crafted by giants for use by their smaller allies.",

    	"Gnome\n"
        " The item is crafted to appear ordinary, and it might look worn. It could also\n"
        " incorporate gears and mechanical components, even if these aren’t essential to the\n"
        " item’s function.",

    	"Undead\n"
        " The item incorporates imagery of death, such as bones and skulls, and it might be\n"
        " crafted from parts of corpses. It feels cold to the touch.")

    history = ("Arcane\n"
        " This item was created for an ancient order of spellcasters and bears the order’s\n"
        " symbol.",

    	"Bane\n"
        " This item was created by the foes of a particular culture or kind of creature. If\n"
        " the culture or creatures are still around, they might recognize the item and single\n"
        " out the bearer as an enemy.",

    	"Heroic\n"
        " A great hero once wielded this item. Anyone who’s familiar with the item’s history\n"
        " expects great deeds from the new owner.",

    	"Ornament\n"
        " The item was created to honor a special occasion. Inset gemstones, gold or platinum\n"
        " inlays, and gold or silver filigree adorn its surface.",

    	"Prophecy\n"
        " The item features in a prophecy: its bearer is destined to play a key role in future\n"
        " events. Someone else who wants to play that role might try to steal the item, or\n"
        " someone who wants to prevent the prophecy from being fulfilled might try to kill the\n"
        " item’s bearer.",

    	"Religious\n"
        " This item was used in religious ceremonies dedicated to a particular deity. It has\n"
        " holy symbols worked into it. The god’s followers might try to persuade its owner to\n"
        " donate it to a temple, steal the item for themselves, or celebrate its use by a\n"
        " cleric or paladin of the same deity.",

    	"Sinister\n"
        " This item is linked to a deed of great evil, such as a massacre or an assassination.\n"
        " It might have a name or be closely associated with a villain who used it. Anyone\n"
        " familiar with the item’s history is likely to treat it and its owner with suspicion.",

    	"Symbol of Power\n"
        " This item was once used as part of royal regalia or as a badge of high office. Its\n"
        " former owner or that person’s descendants might desire it, or someone might\n"
        " mistakenly assume its new owner is the item’s legitimate inheritor.")

    minorProperty = ("Beacon\n"
        " The bearer can use a bonus action to cause the item to shed\n"
        " bright light in a 10-foot radius and dim light for an additional 10\n"
        " feet, or to extinguish the light.",

    	"Compass\n"
        " The wielder can use an action to learn which way is north.",

    	"Conscientious\n"
        " When the bearer of this item contemplates or undertakes a malevolent\n"
        " act, the item enhances pangs of conscience.",

    	"Delver\n"
        " While underground, the bearer of this item always knows the item’s depth below the\n"
        " surface and the direction to the nearest staircase, ramp, or other path leading\n"
        " upward.",

    	"Gleaming\n"
        " This item never gets dirty.",

    	"Guardian\n"
        " The item whispers warnings to its bearer, granting a +2 bonus to initiative if the\n"
        " bearer isn’t incapacitated.",

    	"Harmonious\n"
        " Attuning to this item takes only 1 minute.",

    	"Hidden Message\n"
        " A message is hidden somewhere on the item. It might be visible only at a certain\n"
        " time of the year, under the light of one phase of the moon, or in a specific location.",

    	"Key\n"
        " The item is used to unlock a container, chamber, vault, or other entryway.",

    	"Language\n"
        " The bearer can speak and understand a language of the DM’s choice while the item\n"
        " is on the bearer’s person.",

    	"Sentinel\n"
        " Choose a kind of creature that is an enemy of the item’s creator. This item glows\n"
        " faintly when such creatures are within 120 feet of it.",

    	"Song Craft\n"
        " Whenever this item is struck or is used to strike a foe, its bearer hears a fragment of an\n"
        " ancient song.",

    	"Strange Material\n"
        " The item was created from a material that is bizarre given its purpose. Its durability is\n"
        " unaffected.",

    	"Temperate\n"
        " The bearer suffers no harm in temperatures as cold as −20 degrees Fahrenheit or as warm as\n"
        " 120 degrees Fahrenheit.",

    	"Unbreakable\n"
        " The item can’t be broken. Special means must be used to destroy it.",

    	"War Leader\n"
        " The bearer can use an action to cause his or her voice to carry clearly for up to\n"
        " 300 feet until the end of the bearer’s next turn.",

    	"Waterborne\n"
        " This item floats on water and other liquids. Its bearer has advantage on Strength\n"
        " (Athletics) checks to swim.",

    	"Wicked\n"
        " When the bearer is presented with an opportunity to act in a selfish or malevolent\n"
        " way, the item heightens the bearer’s urge to do so.",

    	"Illusion. The item is imbued with illusion magic, allowing its bearer to alter the\n"
        " item’s appearance in minor ways. Such alterations don’t change how the item is worn,\n"
        " carried, or wielded, and they have no effect on its other magical properties. For\n"
        " example, the wearer could make a red robe appear blue, or make a gold ring look like\n"
        " it’s made of ivory. The item reverts to its true appearance when no one is carrying\n"
        " or wearing it.",

    	" Roll twice, rerolling any additional 20s.")

    quirk = ("Blissful\n"
        " While in possession of the item, the bearer feels fortunate and optimistic\n"
        " about what the future holds. Butterflies and other harmless creatures might\n"
        " frolic in the item’s presence.",

    	"Confident\n"
        " The item helps its bearer feel self-assured.",

    	"Covetous\n"
        " The item’s bearer becomes obsessed with material wealth.",

    	"Frail\n"
        " The item crumbles, frays, chips, or cracks slightly when wielded, worn, or\n"
        " activated. This quirk has no effect on its properties, but if the item has seen\n"
        " much use, it looks decrepit.",

    	"Hungry\n"
        " This item’s magical properties function only if fresh blood from a humanoid has\n"
        " been applied to it within the past 24 hours. It needs only a drop to activate.",

    	"Loud\n"
        " The item makes a loud noise—such as a clang, a shout, or a resonating gong—when used.",

    	"Metamorphic\n"
        " The item periodically and randomly alters its appearance in slight ways. The bearer\n"
        " has no control over these minor alterations, which have no effect on the item’s use.",

    	"Muttering\n"
        " The item grumbles and mutters. A creature who listens carefully to the item might\n"
        " learn something useful.",

    	"Painful\n"
        " The bearer experiences a harmless flash of pain when using the item.",

    	"Possessive\n"
        " The item demands attunement when first wielded or worn, and it doesn’t allow its\n"
        " bearer to attune to other items. (Other items already attuned to the bearer remain\n"
        " so until their attunement ends.)",

    	"Repulsive\n"
        " The bearer feels a sense of distaste when in contact with the item, and continues\n"
        " to sense discomfort while bearing it.",

    	"Slothful\n"
        " The bearer of this item feels slothful and lethargic. While attuned to the item,\n"
        " the bearer requires 10 hours to finish a long rest.")

class StandardArmor:
    lightArmor = (" Light Armor", "Cost", "Armor Class (AC)", "Strength", "Stealth", "Weight",
        " Padded", "5 gp", "11 + Dex modifier", "-", "Disadvantage", "8 lb.", 
        " Leather", "10 gp", "11 + Dex modifier", "-", "-", "10 lb.", 
        " Studded Leather", "45 gp", "12 + Dex Modifier", "-", "-", "13 lb.")

    mediumArmor = (" Medium Armor", "Cost", "Armor Class (AC)", "Strength", "Stealth", "Weight",
        " Hide", "10 gp", "12 + Dex modifier (max 2)", "-", "-", "12 lb.",
        " Chain shirt", "50 gp", "13 + Dex modifier (max 2)", "-", "-", "20 lb.",
        " Scale mail", "50 gp", "14 + Dex modifier (max 2)", "-", "Disadvantage", "45 lb.",
        " Breastplate", "400 gp", "14 + Dex modifier (max 2)", "-", "-", "20 lb.",
        " Half plate", "750 gp", "15 + Dex modifier (max 2)", "-", "Disadvantage", "40 lb.")

    heavyArmor = (" Heavy Armor", "Cost", "Armor Class (AC)", "Strength", "Stealth", "Weight",
        " Ring mail", "30 gp", "14", "-", "Disadvantage", "40 lb.", 
        " Chain mail", "75 gp", "16", "13", "Disadvantage", "55 lb.",
        " Splint", "200 gp","17", "15", "Disadvantage", "60 lb.",
        " Plate", "1,500 gp", "18", "15","Disadvantage","65 lb.")

    shields = (" Shields", 'Cost', "Armor Class (AC)", "Strength", "Stealth", "Weight",
         " Standard Shield", "10 gp", "+2", "-", "-", "6 lb." )

class StandardWeapons:
    simpleMelee = (" Simple Melee" ,"Cost", "Damage", "Weight", "Properties",
        " Club", "1 sp", "1d4 bludgeoning", "2 lb.", "Light",
        " Dagger", "2 gp", "1d4 piercing",  "1 lb.", "Finesse, light, thrown (range 20/60)",
        " Greatclub", "2 sp", "1d8 bludgeoning", "10 lb.", "Two-handed",
        " Handaxe", "5 gp", "1d6 slashing", "2 lb.", "Light, thrown (range 20/60)",
        " Javelin", "5 sp", "1d6 piercing", "2 lb.", "Thrown (range 30/120)",
        " Light Hammer", "2 gp", "1d4 bludgeoning", "2 lb.", "Light, thrown (range 20/60)",
        " Mace", "5 gp", "1d6 bludgeoning", "4 lb.",  "-",
        " Quarterstaff", "2 sp", "1d6 bludgeoning", "4 lb.", "Versatile (1d8)",
        " Sickle", "1 gp", "1d4 slashing", "2 lb.", "Light",
        " Spear", "1 gp", "1d6 piercing", "3 lb.", "Thrown (range 20/60), versatile (1d8)")

    simpleRange = (" Simple Range", "Cost", "Damage",	"Weight", "Properties",
    " Crossbow, light", "25 gp",	"1d8 piercing",	"5 lb.", "Ammunition (range 80/320), loading, two-handed",
    " Dart",	"5 cp",	"1d4 piercing",	"1/4 lb.", "Finesse, thrown (range 20/60)",
    " Shortbow",	"25 gp", "1d6 piercing", "2 lb.", "Ammunition (range 80/320), two-handed",
    " Sling", "1 sp", "1d4 bludgeoning",	"-", "Ammunition (range 30/120)")

    martialMelee = (" Martial Melee", "Cost", "Damage", "Weight", "Properties",
        " Battleaxe", "10 gp", "1d8 slashing", "4 lb.", "Versatile (1d10)",
        " Flail", "10 gp", "1d8 bludgeoning", "2 lb.",	"-",
        " Glaive", "20 gp", "1d10 slashing", "6 lb.", "Heavy, reach, two-handed",
        " Greataxe",	"30 gp", "1d12 slashing", "7 lb.", "Heavy, two-handed",
        " Greatsword", "50 gp", "2d6 slashing", "6 lb.", "Heavy, two-handed",
        " Halberd", "20 gp",	"1d10 slashing", "6 lb.", "Heavy, reach, two-handed",
        " Lance", "10 gp", "1d12 piercing", "6 lb.", "Reach, special",
        " Longsword", "15 gp", "1d8 slashing", "3 lb.", "Versatile (1d10)",
        " Maul", "10 gp", "2d6 bludgeoning", "10 lb.", "Heavy, two-handed",
        " Morningstar", "15 gp", "1d8 piercing", "4 lb.", "-",
        " Pike",	"5 gp",	"1d10 piercing", "18 lb.", "Heavy, reach, two-handed",
        " Rapier", "25 gp",	"1d8 piercing",	"2 lb.", "Finesse",
        " Scimitar",	"25 gp", "1d6 slashing", "3 lb.", "Finesse, light",
        " Shortsword", "10 gp", "1d6 piercing",	"2 lb.", "Finesse, light",
        " Trident",	"5 gp",	"1d6 piercing",	"4 lb.", "Thrown (range 20/60), versatile (1d8)",
        " War Pick",	"5 gp",	"1d8 piercing",	"2 lb.",	"-",
        " Warhammer", "15 gp", "1d8 bludgeoning", "2 lb.", "Versatile (1d10)",
        " Whip",	"2 gp",	"1d4 slashing",	"3 lb.", "Finesse, reach")

    martialRange = (" Martial Range", "Cost", "Damage", "Weight", "Properties",
        " Blowgun",	"10 gp", "1 piercing",	"1 lb.", "Ammunition (range 25/100), loading",
        " Crossbow, hand", "75 gp", "1d6 piercing",	"3 lb.", "Ammunition (range 30/120), light, loading",
        " Crossbow, heavy", "50 gp",	"1d10 piercing", "18 lb.", "Ammunition (range 100/400), heavy, loading, two-handed",
        " Longbow", "50 gp",	"1d8 piercing",	"2 lb.", "Ammunition (range 150/600), heavy, two-handed",
        " Net", "1 gp",	"-", "3 lb.", "Special, thrown (range 5/15)")

class AdventuringGear:
    ammunition = (" Ammunition", "Cost", "Weight",
        " Arrows (20)",	"1 gp",	"1 lb.",
        " Blowgun Needles (50)", "1 gp", "1 lb.",
        " Crossbow Bolts (20)",	"1 gp",	"1 1/2 lb.",
        " Sling Bullets (20)", "4 cp",	"1 1/2 lb.")

    arcaneFocus = (" Arcane Focus", "Cost", "Weight",
        " Crystal",	"10 gp", "1 lb.",
        " Orb",	"20 gp", "3 lb.",
        " Rod",	"10 gp", "2 lb.",
        " Staff", "5 gp", "4 lb.",
        " Wand", "10 gp", "1 lb.")

    druidicFocus = (" Druidic Focus", "Cost", "Weight",
        " Sprig of Mistletoe", "1 gp",	"-",
        " Totem", "1 gp", "-",
        " Wooden Staff",	"5 gp",	"4 lb.",
        " Yew Wand",	"10 gp", "1 lb.")

    holySymbol = (" Holy Symbol", "Cost", "Weight",
        " Amulet", "5 gp", "1 lb.",
        " Emblem", "5 gp", "-",
        " Reliquary", "5 gp", "2 lb.")

    otherGear = (" Adventure Gear", "Cost", "Weight",
        " Abacus", "2 gp",	"2 lb.",
        " Acid (vial)",	"25 gp", "1 lb.",
        " Alchemist's fire (flask)", "50 gp", "1 lb.",
        " Antitoxin (vial)", "50 gp", "-",
        " Backpack", "2 gp", "5 lb.",
        " Ball bearings (bag of 1,000)", "1 gp", "2 lb.",
        " Barrel",	"2 gp",	"70 lb.",
        " Basket",	"4 sp",	"2 lb.",
        " Bedroll",	"1 gp",	"7 lb.",
        " Bell",	"1 gp",	"-",
        " Blanket",	"5 sp",	"3 lb.",
        " Block and tackle", "1 gp", "5 lb.",
        " Book", "25 gp", "5 lb.",
        " Bottle, glass",	"2 gp",	"2 lb.",
        " Bucket",	"5 cp",	"2 lb.",
        " Caltrops (bag of 20)", "1 gp", "2 lb.",
        " Candle",	"1 cp",	"-",
        " Case, crossbow bolt",	"1 gp",	"1 lb.",
        " Case, map or scroll",	"1 gp",	"1 lb.",
        " Chain (10 feet)",	"5 gp",	"10 lb.",
        " Chalk (1 piece)",	"1 cp",	"-",
        " Chest", "5 gp", "25 lb.",
        " Climber's kit", "25 gp", "12 lb.",
        " Clothes, common",	"5 sp",	"3 lb.",
        " Clothes, costume", "5 gp", "4 lb.",
        " Clothes, fine", "15 gp", "6 lb.",
        " Clothes, traveler's",	"2 gp",	"4 lb.",
        " Component pouch",	"25 gp", "2 lb.",
        " Crowbar",	"2 gp",	"5 lb.",
        " Fishing tackle", "1 gp",	"4 lb.",
        " Flask or tankard", "2 cp", "1 lb.",
        " Grappling hook", "2 gp",	"4 lb.",
        " Hammer",	"1 gp",	"3 lb.",
        " Hammer, sledge", "2 gp",	"10 lb.",
        " Healer's kit", "5 gp", "3 lb.",
        " Holy water (flask)",	"25 gp", "1 lb.",
        " Hourglass", "25 gp", "1 lb.",
        " Hunting trap", "5 gp", "25 lb.",
        " Ink (1 ounce bottle)", "10 gp", "-",
        " Ink pen",	"2 cp",	"-",
        " Jug or pitcher", "2 cp", "4 lb.",
        " Ladder (10 foot)", "1 sp", "25 lb.",
        " Lamp", "5 sp", "1 lb.",
        " Lantern, bullseye", "10 gp", "2 lb.",
        " Lantern, hooded",	"5 gp",	"2 lb.",
        " Lock", "10 gp", "1 lb.",
        " Magnifying glass", "100 gp", "-",
        " Manacles", "2 gp", "6 lb.",
        " Mess kit", "2 sp", "1 lb.",
        " Mirror, steel", "5 gp", "1/2 lb.",
        " Oil (flask)",	"1 sp",	"1 lb.",
        " Paper (one sheet)", "2 sp", "-",
        " Parchment (one sheet)", "1 sp", "-",
        " Perfume (vial)", "5 gp", "-",
        " Pick, miner's", "2 gp", "10 lb.",
        " Piton", "5 cp", "1/4 lb.",
        " Poison, basic (vial)", "100 gp", "-",
        " Pole (10-foot)", "5 cp", "7 lb.",
        " Pot, iron", "2 gp", "10 lb.",
        " Potion of healing", "50 gp", "1/2 lb.",
        " Pouch", "5 sp", "1 lb.",
        " Quiver", "1 gp", "1 lb.",
        " Ram, portable", "4 gp", "35 lb.",
        " Rations (1 day)",	"5 sp",	"2 lb.",
        " Robes", "1 gp", "4 lb.",
        " Rope, hempen (50 feet)", "1 gp", "10 lb.",
        " Rope, silk (50 feet)", "10 gp", "5 lb.",
        " Sack", "1 cp", "1/2 lb.",
        " Scale, merchant's", "5 gp", "3 lb.",
        " Sealing wax",	"5 sp",	"-",
        " Shovel", "2 gp", "5 lb.",
        " Signal whistle", "5 cp",	"-",
        " Signet ring"," 5 gp",	"-",
        " Soap", "2 cp", "-",
        " Spellbook", "50 gp", "3 lb.",
        " Spikes, iron (10)", "1 gp", "5 lb.",
        " Spyglass", "1,000 gp", "1 lb.",
        " Tent, two-person", "2 gp", "20 lb.",
        " Tinderbox", "5 sp", "1 lb.",
        " Torch", "1 cp", "1 lb.",
        " Vial", "1 gp", "-",
        " Waterskin (full)", "2 sp", "5 lb.",
        " Whetstone", "1 cp", "1 lb.")

    trinkets = (" A mummified goblin hand",
    	" A piece of crystal that faintly glows in the moonlight",
    	" A gold coin minted in an unknown land",
    	" A diary written in a language you don’t know",
    	" A brass ring that never tarnishes",
    	" An old chess piece made from glass",
    	" A pair of knucklebone dice, each with a skull symbol on the side that would normally show six pips",
    	" A small idol depicting a nightmarish creature that gives you unsettling dreams when you sleep near it",
    	" A rope necklace from which dangles four mummified elf fingers",
    	" The deed for a parcel of land in a realm unknown to you",
    	" A 1-ounce block made from an unknown material",
    	" A small cloth doll skewered with needles",
    	" A tooth from an unknown beast",
    	" An enormous scale, perhaps from a dragon",
    	" A bright green feather",
    	" An old divination card bearing your likeness",
    	" A glass orb filled with moving smoke",
    	" A 1-pound egg with a bright red shell",
    	" A pipe that blows bubbles",
    	" A glass jar containing a weird bit of flesh floating in pickling fluid",
    	" A tiny gnome-crafted music box that plays a song you dimly remember from your childhood",
    	" A small wooden statuette of a smug halfling",
    	" A brass orb etched with strange runes",
    	" A multicolored stone disk",
    	" A tiny silver icon of a raven",
    	" A bag containing forty-seven humanoid teeth, one of which is rotten",
    	" A shard of obsidian that always feels warm to the touch",
    	" A dragon's bony talon hanging from a plain leather necklace",
    	" A pair of old socks",
    	" A blank book whose pages refuse to hold ink, chalk, graphite, or any other substance or marking",
    	" A silver badge in the shape of a five-pointed star",
    	" A knife that belonged to a relative",
    	" A glass vial filled with nail clippings",
    	" A rectangular metal device with two tiny metal cups on one end that throws sparks when wet",
    	" A white, sequined glove sized for a human",
    	" A vest with one hundred tiny pockets",
    	" A small, weightless stone block",
    	" A tiny sketch portrait of a goblin",
    	" An empty glass vial that smells of perfume when opened",
    	" A gemstone that looks like a lump of coal when examined by anyone but you",
    	" A scrap of cloth from an old banner",
    	" A rank insignia from a lost legionnaire",
    	" A tiny silver bell without a clapper",
    	" A mechanical canary inside a gnome-crafted lamp",
    	" A tiny chest carved to look like it has numerous feet on the bottom",
    	" A dead sprite inside a clear glass bottle",
    	" A metal can that has no opening but sounds as if it is filled with liquid, sand, spiders, or broken glass (your choice)",
        " A glass orb filled with water, in which swims a clockwork goldfish",
    	" A silver spoon with an M engraved on the handle",
    	" A whistle made from gold-colored wood",
    	" A dead scarab beetle the size of your hand",
    	" Two toy soldiers, one with a missing head",
    	" A small box filled with different-sized buttons",
    	" A candle that can’t be lit",
    	" A tiny cage with no door",
    	" An old key",
    	" An indecipherable treasure map",
    	" A hilt from a broken sword",
    	" A rabbit’s foot",
    	" A glass eye",
    	" A cameo carved in the likeness of a hideous person",
    	" A silver skull the size of a coin",
    	" An alabaster mask",
    	" A pyramid of sticky black incense that smells very bad",
    	" A nightcap that, when worn, gives you pleasant dreams",
    	" A single caltrop made from bone",
    	" A gold monocle frame without the lens",
    	" A 1-inch cube, each side painted a different color",
    	" A crystal knob from a door",
    	" A small packet filled with pink dust",
    	" A fragment of a beautiful song, written as musical notes on two pieces of parchment",
    	" A silver teardrop earring made from a real teardrop",
    	" The shell of an egg painted with scenes of human misery in disturbing detail",
    	" A fan that, when unfolded, shows a sleeping cat",
    	" A set of bone pipes",
    	" A four-leaf clover pressed inside a book discussing manners and etiquette",
    	" A sheet of parchment upon which is drawn a complex mechanical contraption",
    	" An ornate scabbard that fits no blade you have found so far",
    	" An invitation to a party where a murder happened",
    	" A bronze pentacle with an etching of a rat's head in its center",
    	" A purple handkerchief embroidered with the name of a powerful archmage",
    	" Half of a floorplan for a temple, castle, or some other structure",
    	" A bit of folded cloth that, when unfolded, turns into a stylish cap",
    	" A receipt of deposit at a bank in a far-flung city",
    	" A diary with seven missing pages",
    	" An empty silver snuffbox bearing an inscription on the surface that says “dreams”",
    	" An iron holy symbol devoted to an unknown god",
    	" A book that tells the story of a legendary hero's rise and fall, with the last chapter missing",
    	" A vial of dragon blood",
    	" An ancient arrow of elven design",
    	" A needle that never bends",
    	" An ornate brooch of dwarven design",
    	" An empty wine bottle bearing a pretty label that says, “The Wizard of Wines Winery, Red Dragon Crush, 331422-W”",
    	" A mosaic tile with a multicolored, glazed surface",
    	" A petrified mouse",
    	" A black pirate flag adorned with a dragon's skull and crossbones",
    	" A tiny mechanical crab or spider that moves about when it’s not being observed",
    	" A glass jar containing lard with a label that reads, Griffon Grease",
    	" A wooden box with a ceramic bottom that holds a living worm with a head on each end of its body",
    	" A metal urn containing the ashes of a hero")