kindergarten = ['age', 'appear', 'artist', 'autumn', 'bay', 
                'beak', 'bloom', 'bumpy', 'burst', 'buzz', 
                'care', 'check', 'chilly', 'chore', 'comfort', 
                'community', 'country', 'covered', 'cradle', 
                'dangle', 'decision', 'delicious', 'dentist', 
                'dew', 'disappear', 'drawer', 'dusty', 'edge', 
                'farmer', 'fear', 'firefly', 'fix', 'flipper', 
                'fluffy', 'follow', 'gallop', 'gentle', 'giggle', 
                'glance', 'glossy', 'glow', 'goal', 'gust', 
                'half', 'healthy', 'herd', 'hoof', 'include', 
                'invitation', 'knight', 'laundry', 'lazy', 'leaf', 
                'leak', 'library', 'market', 'melt', 'miserable', 
                'month', 'muddy', 'museum', 'note', 'pace', 'pair', 
                'patient', 'peaceful', 'peck', 'pilot', 'plan', 
                'pointy', 'polite', 'pond', 'president', 'protect', 
                'proud', 'race', 'reach', 'relax', 'rotten', 'round', 
                'row', 'sail', 'scene', 'scrub', 'shade', 'shaky', 
                'ship', 'shore', 'silky', 'sink', 'slide', 'slip', 
                'sniff', 'soapy', 'sparkle', 'spotted', 'spring', 
                'stare', 'summer', 'supplies', 'tangled', 'tent', 
                'tomorrow', 'trade', 'trunk', 'warm', 'wave', 'week', 
                'wiggle', 'winter', 'wish', 'yesterday', 'young']
