class Level:
    header = ("  <tr>\n",
        "    <th>Spell</th>\n",
        "    <th>Level</th>\n",
        "    <th>School</th>\n",
        "    <th>Casting</th>\n",
        "    <th>Range</th>\n",
        "    <th>Duration</th>\n",
        "    <th>Ritual</th>\n",
        "    <th>Con</th>\n",
        "    <th>Classes</th>\n",
        "    <th>Source</th>\n",
        "  </tr>\n")

    cantrips = ("Acid Splash",
        "Blade Ward",
        "Booming Blade",
        "Chill Touch",
        "Control Flames",
        "Create Bonfire",
        "Dancing Lights",
        "Druidcraft",
        "Eldritch Blast",
        "Fire Bolt",
        "Friends",
        "Frostbite",
        "Green Flame Blade",
        "Guidance",
        "Gust",
        "Light",
        "Lightning Lure",
        "Mage Hand",
        "Magic Stone",
        "Mending",
        "Message",
        "Minor Illusion",
        "Mold Earth",
        "Poison Spray",
        "Prestidigitation",
        "Produce Flame",
        "Psychotic Episode",
        "Ray Of Frost",
        "Resistance",
        "Sacred Flame",
        "Shape Water",
        "Shillelagh",
        "Shocking Grasp",
        "Spare The Dying",
        "Sword Burst",
        "Thaumaturgy",
        "Thorn Whip",
        "Thunderclap",
        "Touch Of Madness",
        "True Strike",
        "Vicious Mockery")

    level1Spells = ("Absorb Elements",
        "Alarm",
        "Animal Friendship",
        "Armor Of Agathys",
        "Bane",
        "Beast Bond",
        "Bless",
        "Burning Hands",
        "Ceremony",
        "Charm Person",
        "Chromatic Orb",
        "Color Spray",
        "Command",
        "Compelled Duel",
        "Comprehend Languages",
        "Create Or Destroy Water",
        "Cure Wounds",
        "Detect Evil And Good",
        "Detect Magic",
        "Detect Poison And Disease",
        "Disguise Self",
        "Dissonant Whispers",
        "Divine Favor",
        "Earth Tremor",
        "Ensnaring Strike",
        "Entangle",
        "Expeditious Retreat",
        "Faerie Fire",
        "False Life",
        "Feather Fall",
        "Find Familiar",
        "Fog Cloud",
        "Goodberry",
        "Grease",
        "Guiding Bolt",
        "Hail Of Thorns",
        "Healing Word",
        "Hellish Rebuke",
        "Heroism",
        "Hex",
        "Hunters Mark",
        "Ice Knife",
        "Identify",
        "Illusory Script",
        "Inflict Wounds",
        "Jump",
        "Longstrider",
        "Mage Armor",
        "Magic Missile",
        "Protection From Evil And Good",
        "Purify Food And Drink",
        "Ray Of Sickness",
        "Sanctuary",
        "Searing Smite",
        "Shield",
        "Shield Of Faith",
        "Silent Image",
        "Sleep",
        "Speak With Animals",
        "Tasha's Hideous Laughter",
        "Tenser's Floating Disk",
        "Thunderous Smite",
        "Thunderwave",
        "Unseen Servant",
        "Witch Bolt",
        "Wrathful Smite")

    level2Spells = ("Aganazzar S Scorcher",
        "Aid",
        "Alter Self",
        "Animal Messenger",
        "Arcane Lock",
        "Augury",
        "Barkskin",
        "Beast Sense",
        "Blindness deafness",
        "Blur",
        "Branding Smite",
        "Calm Emotions",
        "Cloud Of Dagger",
        "Continual Flame",
        "Cordon Of Arrows",
        "Crown Of Madness",
        "Darkness",
        "Darkvision",
        "Detect Thoughts",
        "Dust Devil",
        "Earthbind",
        "Enhance Ability",
        "Enlarge / Reduce",
        "Enthrall",
        "Find Steed",
        "Find Traps",
        "Flame Blade",
        "Flaming Sphere",
        "Gentle Repose",
        "Gust Of Wind",
        "Heat Metal",
        "Hold Person",
        "Invisibility",
        "Knock",
        "Lesser Restoration",
        "Levitate",
        "Locate Animals Or Plants",
        "Locate Object",
        "Magic Mouth",
        "Magic Weapon",
        "Maximilian S Earthen Grasp",
        "Melf's Acid Arrow",
        "Mirror Image",
        "Misty Step",
        "Moonbeam",
        "Nystul's Magic Aura",
        "Pass Without Trace",
        "Phantasmal Force",
        "Prayer Of Healing",
        "Protection From Poison",
        "Pyrotechnics",
        "Ray Of Enfeeblement",
        "Rope Trick",
        "Scorching Ray",
        "See Invisibility",
        "Shatter",
        "Silence",
        "Skywrite",
        "Snilloc's Snowball Swarm",
        "Spider Climb",
        "Spike Growth",
        "Spiritual Weapon",
        "Suggestion",
        "Warding Bond",
        "Warding Wind",
        "Web",
        "Zone Of Truth")

    level3Spells = ("Animate Dead",
        "Aura Of Vitality",
        "Beacon Of Hope",
        "Bestow Curse",
        "Blinding Smite",
        "Blink",
        "Call Lightning",
        "Clairvoyance",
        "Conjure Animals",
        "Conjure Barrage",
        "Counterspell",
        "Create Food And Water",
        "Crusader S Mantle",
        "Daylight",
        "Dispel Magic",
        "Elemental Weapon",
        "Erupting Earth",
        "Fear",
        "Feign Death",
        "Fireball",
        "Flame Arrows",
        "Fly",
        "Gaseous Form",
        "Glyph Of Warding",
        "Haste",
        "Hunger Of Hadar",
        "Hypnotic Pattern",
        "Leomund S Tiny Hut",
        "Lightning Arrow",
        "Lightning Bolt",
        "Magic Circle",
        "Major Image",
        "Mass Healing Word",
        "Meld Into Stone",
        "Melf's Minute Meteors",
        "Nondetection",
        "Phantom Steed",
        "Plant Growth",
        "Protection From Energy",
        "Remove Curse",
        "Revivify",
        "Sending",
        "Sleet Storm",
        "Slow",
        "Speak With Dead",
        "Speak With Plants",
        "Spirit Guardians",
        "Stinking Cloud",
        "Tidal Wave",
        "Tongues",
        "Vampiric Touch",
        "Wall Of Sand",
        "Wall Of Water",
        "Water Breathing",
        "Water Walk",
        "Wind Wall")

    level4Spells = ("Arcane Eye",
        "Aura Of Life",
        "Aura Of Purity",
        "Banishment",
        "Blight",
        "Compulsion",
        "Confusion",
        "Conjure Minor Elementals",
        "Conjure Woodland Beings",
        "Control Water",
        "Death Ward",
        "Dimension Door",
        "Divination",
        "Dominate Beast",
        "Elemental Bane",
        "Evard's Black Tentacles",
        "Fabricate",
        "Find Greater Steed",
        "Fire Shield",
        "Freedom Of Movement",
        "Giant Insect",
        "Grasping Vine",
        "Greater Invisibility",
        "Guardian Of Faith",
        "Hallucinatory Terrain",
        "Ice Storm",
        "Leomund's Secret Chest",
        "Locate Creature",
        "Mordenkainen's Faithful Hound",
        "Mordenkainen's Private Sanctum",
        "Otiluke's Resilient Sphere",
        "Phantasmal Killer",
        "Polymorph",
        "Staggering Smite",
        "Stone Shape",
        "Stoneskin",
        "Storm Sphere",
        "Vitriolic Sphere",
        "Wall Of Fire",
        "Watery Sphere")

    level5Spells = ("Animate Objects",
    	"Antilife Shell",
    	"Arcane Hand",
       	"Awaken",
    	"Banishing Smite",
    	"Circle Of Power",
    	"Cloudkill",
    	"Commune",
    	"Commune With Nature",
    	"Cone Of Cold",
    	"Conjure Elemental",
    	"Conjure Volley",
    	"Contact Other Plane",
    	"Contagion",
    	"Control Winds",
    	"Creation",
    	"Destructive Wave",
    	"Dispel Evil And Good",
      	"Dominate Person",
    	"Dream",
    	"Flame Strike",
       	"Geas",
    	"Greater Restoration",
    	"Hallow",
    	"Hold Monster",
    	"Immolation",
    	"Insect Plague",
    	"Legend Lore",
    	"Maelstrom",
    	"Mass Cure Wounds",
    	"Mislead",
    	"Modify Memory",
    	"Passwall",
    	"Planar Binding",
    	"Raise Dead",
    	"Reincarnate",
        "Scrying",
    	"Seeming",
    	"Swift Quiver",
    	"Telekinesis",
    	"Telepathic Bond",
    	"Teleportation Circle",
    	"Transmute Rock",
    	"Tree Stride",
    	"Wall Of Force",
    	"Wall Of Stone")

    level6Spells = ("Arcane Gate",
        "Blade Barrier",
        "Bones of the Earth",
        "Chain Lightning",
        "Circle Of Death",
        "Conjure Fey",
        "Contingency",
        "Create Undead",
        "Disintegrate",
        "Eyebite",
        "Find The Path",
        "Flesh To Stone",
        "Forbiddance",
        "Freezing Sphere",
        "Globe Of Invulnerability",
        "Guards And Wards",
        "Harm",
        "Heal",
        "Heroes' Feast",
        "Instant Summons",
        "Investiture of Flame",
        "Investiture of Ice",
        "Investiture of Stone",
        "Investiture of Wind",
        "Irresistible Dance",
        "Magic Jar",
        "Mass Suggestion",
        "Move Earth",
        "Planar Ally",
        "Primordial Ward",
        "Programmed Illusion",
        "Sunbeam",
        "Transport Via Plants",
        "True Seeing",
        "Wall Of Ice",
        "Wall Of Thorns",
        "Wind Walk",
        "Word Of Recall")

    level7Spells = ("Arcane Sword",
        "Conjure Celestial",
        "Delayed Blast Fireball",
        "Divine Word",
        "Etherealness",
        "Finger Of Death",
        "Fire Storm",
        "Forcecage",
        "Magnificent Mansion",
        "Mirage Arcane",
        "Plane Shift",
        "Prismatic Spray",
        "Project Image",
        "Regenerate",
        "Resurrection",
        "Reverse Gravity",
        "Sequester",
        "Simulacrum",
        "Symbol",
        "Teleport",
        "Whirlwind")

    level8Spells = ("Animal Shapes",
        "Antimagic Field",
        "Antipathy/sympathy",
        "Clone",
        "Control Weather",
        "Demiplane",
        "Dominate Monster",
        "Earthquake",
        "Feeblemind",
        "Glibness",
        "Holy Aura",
        "Horrid Wilting",
        "Incendiary Cloud",
        "Maze",
        "Mind Blank",
        "Power Word Stun",
        "Sunburst",
        "Telepathy",
        "Tsunami")

    level9Spells = ("Astral Projection",
        "Foresight",
        "Gate",
        "Imprisonment",
        "Mass Heal",
        "Meteor Swarm",
        "Power Word Heal",
        "Power Word Kill",
        "Prismatic Wall",
        "Shapechange",
        "Storm Of Vengeance",
        "Time Stop",
        "True Polymorph",
        "True Resurrection",
        "Weird",
        "Wish")